version: "3.8"

services:
    web:
        build: ./flask_app
        ports:
            - "5000:5000"
        environment:
            - REDIS_URL=redis://redis:6379
        depends_on:
            - redis

    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
db:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"